apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-pulse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluster-pulse
  template:
    metadata:
      labels:
        app: cluster-pulse
    spec:
      containers:
      - name: cluster-pulse
        image: masumosman/cluster-pulse:latest
        ports:
        - containerPort: 8080